# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: file-share_development

test:
  <<: *default
  database: file-share_test

production:
  url: <%= ENV["DATABASE_URL"] %>
